### ISSUE TITLE
Not on npm

### ISSUE THREAD

**Issue by tmoc** [harryoh/generator-coffee-fullstack#5]
npm install results in: npm ERR! 404 Not Found

Does not appear to be on npm: https://www.npmjs.com/search?q=generator-coffee-fullstack

**Comment by harryoh** [comment]
I tested it but it seems wrong.
I will test it again and fix it.

Thanks a lot

**Comment by harryoh** [comment]
I published this module previously but I think it is removed on npm repository.
I published it, again and my eyes will be on it.
